resolver: lts-6.9
packages:
- '.'
- '../lnforum-api'
- '../lnforum-sanitize'
- '../lnforum-validate'
- '../lnforum-types-gen'
- '../haskell-api-helpers'
- '../haskell-api-helpers-shared'
- '../haskell-ebyam'
- '../haskell-rehtie'
- '../haskell-ifte'
- '../haskell-either-helpers'
- '../web-routes'
extra-deps: []
flags: {}
extra-package-dbs: []
